# update_version.ps1
# Updates version information in import_exports.h with current UTC timestamp during pre-build events.
# Also regenerates colors_dev.map for Linux symbol versioning.

$readMe        = "$PSScriptRoot\README.md"
$importExports = "$PSScriptRoot\import_exports.h"
$mapFile       = "$PSScriptRoot\colors_dev.map"
$utcNow        = [DateTime]::UtcNow

# Calculate components
$fullYear   = $utcNow.Year
$yearOffset = $fullYear - 2020
$month      = $utcNow.Month
$day        = $utcNow.Day
$time       = $utcNow.ToString("HHmm")

# ---------------------------------------------------------------------------
# 1. Update import_exports.h
# ---------------------------------------------------------------------------
$content = Get-Content $importExports -Raw

$content = $content -replace '(#define COLORS_DEV_FULL_YEAR\s+)\d+',  "`${1}$fullYear"
$content = $content -replace '(#define COLORS_DEV_YEAR_OFFSET\s+)\d+', "`${1}$yearOffset"
$content = $content -replace '(#define COLORS_DEV_MONTH\s+)\d+',       "`${1}$month"
$content = $content -replace '(#define COLORS_DEV_DAY\s+)\d+',         "`${1}$day"
$content = $content -replace '(#define COLORS_DEV_UTC_TIME\s+)\d+',    "`${1}$time"

Set-Content $importExports -Value $content -NoNewline
Write-Host "Version updated: $yearOffset.$month.$day.$time"

# ---------------------------------------------------------------------------
# 2. Regenerate colors_dev.map (Linux ELF symbol version script)
#    Scrape every COLORS_DEV_API declaration from the public headers and emit
#    a versioned export map so the .so soname tracks the same major version.
# ---------------------------------------------------------------------------
$versionTag = "COLORS_DEV_$yearOffset.$month"

# Collect exported symbol names from all public headers
$symbols = Select-String -Path "$PSScriptRoot\*.h" -Pattern 'COLORS_DEV_API\s+\S+\s+(\w+)\s*\(' |
    ForEach-Object {
        if ($_.Line -match 'COLORS_DEV_API\s+\S+\s+(\w+)\s*\(') { $Matches[1] }
        # Handle two-token return types like "colors_dev_float64 GetHue"
        elseif ($_.Line -match 'COLORS_DEV_API\s+\S+\s+\S+\s+(\w+)\s*\(') { $Matches[1] }
    } | Where-Object { $_ -and $_ -ne 'COLORS_DEV_API' } | Sort-Object -Unique

$mapLines = @()
$mapLines += "# Auto-generated by update_version.ps1 - do not edit manually"
$mapLines += "# Linux ELF symbol version script for libcolors_dev.so"
$mapLines += "# Version tag: $versionTag"
$mapLines += ""
$mapLines += "$versionTag {"
$mapLines += "    global:"
foreach ($sym in $symbols) {
    $mapLines += "        $sym;"
}
$mapLines += "    local:"
$mapLines += "        *;"
$mapLines += "};"

Set-Content $mapFile -Value ($mapLines -join "`n") -NoNewline
Write-Host "Symbol map written: $mapFile  ($($symbols.Count) symbols, tag: $versionTag)"
